# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0005_auto_20180507_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='is_approved',
            new_name='manager_approved',
        ),
        migrations.AddField(
            model_name='leave',
            name='supervisor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
