# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0006_auto_20180510_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
