# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0009_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
    ]
