# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0011_auto_20180520_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 20, 17, 39, 7, 940673, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
