# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0014_auto_20180530_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, null=True),
        ),
    ]
